// @vitest-environment node
/**
 * Drift guard for THIS repo's dogfood hook configs.
 *
 * These configs are hand-maintained, are not generated by `integrations.ts`,
 * and nothing else in the suite reads them — so when one drifts, it drifts
 * silently and the repo simply stops enforcing its own policies. That is not
 * hypothetical: when #337 landed, the opencode dev shim drifted and
 * `block-read-outside-cwd` no-op'd on every opencode read in this repo,
 * unnoticed. This file is the tripwire.
 *
 * It asserts the *dev* form. The production `npx -y failproofai` form that
 * users install is covered separately by __tests__/hooks/integrations.test.ts.
 */
import { describe, it, expect } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = process.cwd();
const LAUNCHER = "scripts/dev-hook.mjs";

/** Keys that hold a shell command. `bash`/`powershell` are Copilot's schema. */
const COMMAND_KEYS = new Set(["command", "bash", "powershell"]);

/**
 * The five dogfood schemas differ wildly (Claude-nested, Cursor-flat, Factory
 * top-level-keys, Antigravity named-hook, Copilot bash+powershell). Rather than
 * encode all five, walk the tree and pick up anything that looks like one of
 * our commands — new schemas come along for free.
 */
function collectHookCommands(node: unknown, out: string[] = []): string[] {
  if (Array.isArray(node)) {
    for (const v of node) collectHookCommands(v, out);
    return out;
  }
  if (node && typeof node === "object") {
    for (const [k, v] of Object.entries(node)) {
      if (typeof v === "string" && COMMAND_KEYS.has(k) && v.includes("failproofai")) out.push(v);
      else collectHookCommands(v, out);
    }
  }
  return out;
}

function commandsIn(file: string): string[] {
  return collectHookCommands(JSON.parse(readFileSync(resolve(ROOT, file), "utf8")));
}

/**
 * Events where exit 2 means "don't finish, retry". A shell guard can't read
 * `stop_hook_active` off stdin to know it's already retrying, so it must not
 * deny here — it would loop forever. Everything else gets exit 2, which
 * genuinely blocks on Claude/Factory/Goose and surfaces loudly elsewhere.
 */
const STOP_CLASS = new Set(["Stop", "StopFailure", "SubagentStop", "stop", "subagentStop"]);

const CONFIGS = [
  { file: ".claude/settings.json", cli: null, count: 26 },
  { file: ".codex/hooks.json", cli: "codex", count: 6 },
  { file: ".github/hooks/failproofai.json", cli: "copilot", count: 12 }, // 6 events × bash+powershell
  { file: ".cursor/hooks.json", cli: "cursor", count: 6 },
  { file: ".factory/hooks.json", cli: "factory", count: 9 },
  { file: ".devin/config.json", cli: "devin", count: 7 },
  { file: ".agents/hooks.json", cli: "antigravity", count: 4 },
  { file: ".agents/plugins/failproofai/hooks/hooks.json", cli: "goose", count: 5 },
];

describe.each(CONFIGS)("$file", ({ file, cli, count }) => {
  it(`registers exactly ${count} failproofai commands`, () => {
    // Catches an event silently dropped during a hand-edit.
    expect(commandsIn(file)).toHaveLength(count);
  });

  it("routes every command through the dev launcher", () => {
    // .claude quotes the path so a $CLAUDE_PROJECT_DIR containing spaces still
    // resolves; the others pass it bare.
    for (const cmd of commandsIn(file)) expect(cmd).toMatch(/scripts\/dev-hook\.mjs"? --hook /);
  });

  it("never spawns bun directly", () => {
    // The whole point: `bun ...` dies with exit 127 when bun is off the hook's
    // PATH, and the session runs unenforced without saying so.
    for (const cmd of commandsIn(file)) expect(cmd).not.toMatch(/(^|[|;&\s])bun\s/);
  });

  it("never uses the production npx form", () => {
    // `failproofai policies --install --scope project` run inside this repo
    // would rewrite these to npx, which enforces the *published* package
    // against the working tree. That is the #337 class of silent wrongness.
    for (const cmd of commandsIn(file)) expect(cmd).not.toContain("npx -y failproofai");
  });

  it("guards on node before invoking the launcher, never after", () => {
    // A reactive `launcher || fallback` chain would re-fire the fallback on
    // every legitimate exit-2 denial. The check must precede the launcher.
    for (const cmd of commandsIn(file)) {
      expect(cmd).toMatch(/^(command -v node|if \(-not \(Get-Command node)/);
      expect(cmd).not.toMatch(/dev-hook\.mjs[^;]*\|\|/);
    }
  });

  it("exits 1 on stop-class events and 2 everywhere else", () => {
    for (const cmd of commandsIn(file)) {
      const event = /--hook (\S+)/.exec(cmd)?.[1];
      expect(event).toBeDefined();
      const expected = STOP_CLASS.has(event!) ? 1 : 2;
      expect(`${event} → exit ${/exit (\d)/.exec(cmd)?.[1]}`).toBe(`${event} → exit ${expected}`);
    }
  });

  if (cli) {
    it(`passes --cli ${cli}`, () => {
      for (const cmd of commandsIn(file)) expect(cmd).toContain(`--cli ${cli}`);
    });
  } else {
    it("omits --cli, relying on the cli=claude default", () => {
      for (const cmd of commandsIn(file)) expect(cmd).not.toContain("--cli ");
    });
  }
});

describe("copilot's dual-shell schema", () => {
  const file = ".github/hooks/failproofai.json";

  it("uses the POSIX guard on bash and the PowerShell guard on powershell", () => {
    const cfg = JSON.parse(readFileSync(resolve(ROOT, file), "utf8"));
    const entries: { bash?: string; powershell?: string }[] = [];
    const walk = (n: unknown): void => {
      if (Array.isArray(n)) return n.forEach(walk);
      if (n && typeof n === "object") {
        const o = n as Record<string, unknown>;
        if (typeof o.bash === "string" && typeof o.powershell === "string") {
          entries.push(o as { bash: string; powershell: string });
        }
        Object.values(o).forEach(walk);
      }
    };
    walk(cfg);

    expect(entries).toHaveLength(6);
    for (const e of entries) {
      expect(e.bash).toMatch(/^command -v node/);
      expect(e.powershell).toMatch(/^if \(-not \(Get-Command node/);
      // `command -v` is not a PowerShell builtin; shipping it there would make
      // the guard itself the thing that fails.
      expect(e.powershell).not.toContain("command -v");
    }
  });
});

describe("the surfaces that spawn bun from JS rather than a config", () => {
  it("the opencode dev shim resolves bun via the shared resolver", () => {
    const src = readFileSync(resolve(ROOT, ".opencode/plugins/failproofai.mjs"), "utf8");
    expect(src).toContain("resolveDevSpawn");
    // Strip comments — prose is free to mention the anti-pattern it warns about.
    const code = src.replace(/\/\*[\s\S]*?\*\//g, "").replace(/^\s*\/\/.*$/gm, "");
    expect(code).not.toMatch(/spawnSync\(\s*"bun"/);
  });

  /**
   * Known gap, encoded deliberately. `.pi/settings.json` loads
   * `pi-extension/index.ts`, whose resolveSpawn() has the same bare-"bun"
   * fallback — but that file ships to users in the npm tarball, where
   * dist-first is the correct order. Fixing it means changing shipped
   * behaviour, so it is out of scope here. This test documents the hole so
   * nobody mistakes it for coverage.
   */
  it("pi's dogfood surface is knowingly NOT protected", () => {
    const src = readFileSync(resolve(ROOT, "pi-extension/index.ts"), "utf8");
    expect(src).toContain('cmd: "bun"');
  });
});

describe("repo-wide invariants", () => {
  it("the launcher every config points at exists", () => {
    expect(existsSync(resolve(ROOT, LAUNCHER))).toBe(true);
  });

  it("the hook-sync image still installs bun", () => {
    // The launcher only *finds* bun; it cannot conjure it. That container runs
    // headless with no bun of its own, so without this layer the
    // require-*-before-stop policies driving its auto-PR never fire.
    const dockerfile = readFileSync(resolve(ROOT, "docker-hook-sync/Dockerfile"), "utf8");
    expect(dockerfile).toMatch(/bun/i);
  });
});
